### PR TITLE
flex panel gallery

### PR DESCRIPTION
**Pull request by Pishuhott**

### CODE REVIEW

**Comment by castortroy06** [comment]
@Pishuhott Please, don't forget about styleguides

**Comment by Pishuhott** [comment]
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-6-flex-panel-gallery-10

**Comment by castortroy06** [comment]
@Pishuhott Please, remove `open` and `open-active` classes from all the panels on click.

**Comment by Pishuhott** [comment]
> @Pishuhott Пожалуйста, удалить `open`и `open-active`классы из всех панелей на мыши.

corrected

**Pull request merged**
